class ContentHandler {
  constructor(content) {
    this.content = content;
  }
  element(element) {
    element.setAttribute("content", this.content);
  }
}

const prefix = "/profile/";

export async function onRequest(context) {
  const { request, next } = context;
  const res = await next();
  const { pathname } = new URL(request.url);

  if (!pathname.startsWith(prefix)) {
    return res;
  }

  const username = pathname.substring(prefix.length);
  const profile = fetchProfile(username);
  const lbRank = profile.allTimeLbs.time[60].english;

  const age =Math.floor((Date.now()- profile.addedAt )/ (1000 * 60 * 60 * 24));
  const timeTyping = Math.round(profile.typingStats.timeTyping/60/60);

  const title = `${profile.name}'s profile on monkeytype.com`;
  const description = `${profile.name} typed for ${timeTyping} hours. Highest typing speed is ${
    profile.personalBests.time[60][0].wpm
  }wpm, faster then ${Math.round(100 - (lbRank.rank / lbRank.count) * 100)}%. Joined ${age} days ago. Currently on a ${profile.streak} day streak.`;
  const image = `https://cdn.discordapp.com/avatars/${profile.discordId}/${profile.discordAvatar}.png?size=256`;

  return new HTMLRewriter()
    .on('meta[property="og:description"]', new ContentHandler(description))
    .on('meta[property="og:title"]', new ContentHandler(title))
    .on('meta[name="twitter:title"]', new ContentHandler(title))
    .on('meta[property="og:image"]', new ContentHandler(image))
    .on('meta[name="twitter:image"]', new ContentHandler(image))
    
    .transform(res);
}

function fetchProfile(username) {
    //TODO fetch from api instead
  return {
    name: "fehmer",
    addedAt: 1617961075000,
    typingStats: {
      completedTests: 8178,
      startedTests: 9268,
      timeTyping: 452355.7503850213,
    },
    personalBests: {
      time: {
        15: [
          {
            acc: 97.14,
            consistency: 66.61,
            difficulty: "normal",
            lazyMode: false,
            language: "english_1k",
            punctuation: false,
            raw: 81.56,
            wpm: 81.56,
            timestamp: 1692084854951,
          },
          {
            acc: 89.9,
            consistency: 76.01,
            difficulty: "normal",
            lazyMode: false,
            language: "code_java",
            punctuation: false,
            raw: 74.4,
            wpm: 70.4,
            timestamp: 1638128688838,
          },
          {
            acc: 100,
            consistency: 85.73,
            difficulty: "normal",
            lazyMode: false,
            language: "english",
            punctuation: false,
            raw: 116.77,
            wpm: 116.77,
            timestamp: 1708516519325,
          },
          {
            acc: 96.51,
            consistency: 71.19,
            difficulty: "normal",
            lazyMode: false,
            language: "english_10k",
            punctuation: false,
            raw: 66.4,
            wpm: 66.4,
            timestamp: 1679098671445,
          },
          {
            acc: 96.67,
            consistency: 55.74,
            difficulty: "normal",
            lazyMode: false,
            language: "german",
            punctuation: false,
            raw: 65.6,
            wpm: 65.6,
            timestamp: 1702566281433,
          },
          {
            acc: 94.23,
            consistency: 67.34,
            difficulty: "normal",
            lazyMode: true,
            language: "german",
            punctuation: false,
            raw: 78.36,
            wpm: 78.36,
            timestamp: 1699317945454,
          },
          {
            acc: 90,
            consistency: 67.41,
            difficulty: "normal",
            lazyMode: false,
            language: "code_ook",
            punctuation: false,
            raw: 28.79,
            wpm: 28.79,
            numbers: false,
            timestamp: 1710607532185,
          },
        ],
        30: [
          {
            acc: 99.22,
            consistency: 79.19,
            difficulty: "normal",
            lazyMode: false,
            language: "english",
            punctuation: false,
            raw: 102,
            wpm: 102,
            timestamp: 1688032887645,
          },
          {
            acc: 96.05,
            consistency: 74.35,
            difficulty: "normal",
            lazyMode: false,
            language: "english_1k",
            punctuation: false,
            raw: 68.8,
            wpm: 68,
            timestamp: 1639389712393,
          },
        ],
        60: [
          {
            acc: 98.88,
            punctuation: false,
            timestamp: 1719060392470,
            raw: 105.79,
            difficulty: "normal",
            wpm: 105.79,
            consistency: 83.04,
            language: "english",
            lazyMode: false,
            numbers: false,
          },
          {
            acc: 93.59,
            timestamp: 1628106083694,
            punctuation: false,
            difficulty: "normal",
            raw: 44.4,
            consistency: 66.07,
            language: "english_10k",
            wpm: 40.4,
          },
          {
            raw: 86.99,
            difficulty: "normal",
            punctuation: false,
            consistency: 79.5,
            language: "english_1k",
            wpm: 86.99,
            timestamp: 1724698819798,
            acc: 99.09,
            lazyMode: false,
            numbers: false,
          },
          {
            acc: 92.67,
            punctuation: true,
            raw: 50,
            consistency: 63.8,
            difficulty: "normal",
            language: "english_1k",
            timestamp: 1628188381434,
            wpm: 50,
          },
          {
            acc: 91.1,
            consistency: 64.72,
            difficulty: "normal",
            lazyMode: false,
            language: "german_10k",
            punctuation: false,
            raw: 52.59,
            wpm: 52.59,
            timestamp: 1690021778774,
          },
          {
            acc: 93.46,
            consistency: 66.87,
            difficulty: "normal",
            lazyMode: false,
            language: "english_450k",
            punctuation: false,
            raw: 56.59,
            wpm: 56.59,
            timestamp: 1698509565991,
          },
          {
            acc: 93.73,
            consistency: 69.05,
            difficulty: "normal",
            lazyMode: true,
            language: "german",
            punctuation: false,
            raw: 70.8,
            wpm: 69.6,
            timestamp: 1715038487565,
            numbers: false,
          },
          {
            acc: 91.63,
            consistency: 62.36,
            difficulty: "normal",
            lazyMode: false,
            language: "german_250k",
            punctuation: false,
            raw: 42.39,
            wpm: 42.39,
            timestamp: 1700763795439,
          },
          {
            acc: 91.96,
            consistency: 64.27,
            difficulty: "normal",
            lazyMode: false,
            language: "german",
            punctuation: false,
            raw: 70.58,
            wpm: 66.58,
            timestamp: 1702959250107,
          },
          {
            acc: 95.39,
            consistency: 67.06,
            difficulty: "normal",
            lazyMode: false,
            language: "english",
            punctuation: true,
            raw: 81.78,
            wpm: 81.78,
            timestamp: 1708792551514,
          },
          {
            acc: 94.9,
            consistency: 69.46,
            difficulty: "normal",
            lazyMode: false,
            language: "code_ook",
            punctuation: false,
            raw: 36.59,
            wpm: 36.59,
            numbers: false,
            timestamp: 1710605642961,
          },
          {
            acc: 88.13,
            consistency: 54.81,
            difficulty: "normal",
            lazyMode: true,
            language: "klingon",
            punctuation: false,
            raw: 27.4,
            wpm: 27.4,
            numbers: false,
            timestamp: 1710605959745,
          },
          {
            acc: 94.84,
            consistency: 68.72,
            difficulty: "normal",
            lazyMode: false,
            language: "code_systemverilog",
            punctuation: false,
            raw: 69.8,
            wpm: 68.8,
            numbers: false,
            timestamp: 1710952804219,
          },
          {
            acc: 93.33,
            consistency: 68.09,
            difficulty: "normal",
            lazyMode: true,
            language: "italian",
            punctuation: false,
            raw: 65.6,
            wpm: 65.6,
            numbers: false,
            timestamp: 1715022577013,
          },
          {
            acc: 96.49,
            consistency: 69.93,
            difficulty: "normal",
            lazyMode: true,
            language: "french",
            punctuation: false,
            raw: 70.8,
            wpm: 70.8,
            numbers: false,
            timestamp: 1715038583877,
          },
          {
            acc: 91.99,
            consistency: 71.31,
            difficulty: "normal",
            lazyMode: true,
            language: "spanish",
            punctuation: false,
            raw: 56.6,
            wpm: 56.6,
            numbers: false,
            timestamp: 1715038665697,
          },
        ],
        120: [
          {
            timestamp: 1638890346979,
            acc: 94.54,
            wpm: 58.6,
            consistency: 66.99,
            difficulty: "normal",
            raw: 58.6,
            language: "english_1k",
            punctuation: true,
            lazyMode: false,
          },
          {
            acc: 95.89,
            consistency: 61.09,
            difficulty: "normal",
            lazyMode: false,
            language: "code_kotlin",
            punctuation: false,
            raw: 58.1,
            wpm: 58.1,
            timestamp: 1637678533466,
          },
          {
            acc: 92.31,
            consistency: 67.98,
            difficulty: "normal",
            lazyMode: false,
            language: "code_java",
            punctuation: false,
            raw: 65.69,
            wpm: 61.09,
            timestamp: 1638128556789,
          },
          {
            acc: 89.76,
            consistency: 52.61,
            difficulty: "normal",
            lazyMode: false,
            language: "code_java",
            punctuation: true,
            raw: 48.6,
            wpm: 48.6,
            timestamp: 1638128865243,
          },
          {
            acc: 94.61,
            consistency: 74.73,
            difficulty: "normal",
            lazyMode: false,
            language: "english_1k",
            punctuation: false,
            raw: 65.09,
            wpm: 64.29,
            timestamp: 1639233418544,
          },
          {
            acc: 98.15,
            consistency: 76.67,
            difficulty: "normal",
            lazyMode: false,
            language: "english",
            punctuation: false,
            raw: 95.2,
            wpm: 95.2,
            timestamp: 1713026130724,
            numbers: false,
          },
        ],
      },
      words: {
        10: [
          {
            acc: 100,
            consistency: 88.36,
            difficulty: "normal",
            lazyMode: false,
            language: "english_1k",
            punctuation: false,
            raw: 108.97,
            wpm: 108.97,
            timestamp: 1691058951682,
          },
          {
            acc: 100,
            consistency: 60.27,
            difficulty: "normal",
            lazyMode: false,
            language: "english",
            punctuation: false,
            raw: 131.39,
            wpm: 131.39,
            timestamp: 1677499406840,
          },
        ],
        25: [
          {
            wpm: 112.23,
            punctuation: false,
            difficulty: "normal",
            timestamp: 1692705512427,
            raw: 112.23,
            acc: 100,
            consistency: 89.96,
            language: "english",
            lazyMode: false,
          },
          {
            acc: 99.32,
            consistency: 80.13,
            difficulty: "normal",
            lazyMode: false,
            language: "english_1k",
            punctuation: false,
            raw: 79.96,
            wpm: 79.96,
            timestamp: 1640557872171,
          },
          {
            acc: 95.29,
            consistency: 73.07,
            difficulty: "normal",
            lazyMode: false,
            language: "git",
            punctuation: false,
            raw: 72.95,
            wpm: 72.95,
            timestamp: 1640886840946,
          },
          {
            acc: 95.05,
            consistency: 69.13,
            difficulty: "normal",
            lazyMode: false,
            language: "code_javascript",
            punctuation: false,
            raw: 59.41,
            wpm: 59.41,
            timestamp: 1640965657797,
          },
        ],
        50: [
          {
            acc: 95,
            consistency: 70.05,
            difficulty: "normal",
            lazyMode: false,
            language: "english_1k",
            punctuation: false,
            raw: 65.68,
            wpm: 65.68,
            timestamp: 1639389802834,
          },
          {
            acc: 98.41,
            consistency: 71.19,
            difficulty: "normal",
            lazyMode: false,
            language: "english",
            punctuation: false,
            raw: 97.36,
            wpm: 95.8,
            timestamp: 1688066380708,
          },
          {
            acc: 100,
            consistency: 75.1,
            difficulty: "normal",
            lazyMode: false,
            language: "english",
            punctuation: true,
            raw: 79.26,
            wpm: 79.26,
            timestamp: 1662044489642,
          },
        ],
        100: [
          {
            acc: 93.36,
            consistency: 66.46,
            difficulty: "normal",
            lazyMode: false,
            language: "english_1k",
            punctuation: false,
            raw: 62.84,
            wpm: 61.67,
            timestamp: 1640350065462,
          },
          {
            acc: 98.11,
            consistency: 78.96,
            difficulty: "normal",
            lazyMode: false,
            language: "english",
            punctuation: false,
            raw: 91.07,
            wpm: 89.85,
            timestamp: 1685265952527,
          },
        ],
      },
    },
    discordId: "727050199893016606",
    discordAvatar: "412250e175615757700ea2d2f62185c0",
    xp: 2545531,
    streak: 142,
    maxStreak: 333,
    isPremium: false,
    inventory: {
      badges: [
        {
          id: 2,
          selected: true,
        },
      ],
    },
    details: {
      bio: "> We do these things not because they are easy, but because we thought they were going to be easy",
      keyboard:
        "- HMKB 60\n- boardwalk layout\n- T1 blue lotus switches\n- SA Recall keycaps",
      socialProfiles: {
        github: "fehmer",
        twitter: "",
        website: "https://keebs.fehmer.info/",
      },
    },
    allTimeLbs: {
      time: {
        15: {
          english: {
            rank: 93341,
            count: 332413,
          },
        },
        60: {
          english: {
            rank: 53332,
            count: 329119,
          },
        },
      },
    },
    uid: "TKTTZWnDq4QBfIwgJ42KdE3wAYw1",
  };
}
